version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "wojsmol"
      - "zwiastunsw"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "wojsmol"
      - "zwiastunsw"
      
  - package-ecosystem: "npm"
    directory: "/src/style-guide/builder"
    schedule:
      interval: "daily"
    reviewers:
      - "wojsmol"
      - "zwiastunsw"

